# Generated by Django 5.2.17 on 2026-10-05 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_selfierecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jewel Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_24k', models.IntegerField(default=7980, help_text='Rate in INR per gram for 24K (999 pure gold)')),
                ('gold_22k', models.IntegerField(default=7450, help_text='Rate in INR per gram for 22K (916 hallmark gold)')),
                ('gold_18k', models.IntegerField(default=6100, help_text='Rate in INR per gram for 18K (750 gold)')),
                ('silver_999', models.DecimalField(decimal_places=2, default=98.5, help_text='Rate in INR per gram for 999 fine silver', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JewelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], default='Gold', max_length=20)),
                ('purity', models.CharField(choices=[('24K', '24K (999 Fine Gold)'), ('22K', '22K (BIS 916 Hallmark)'), ('18K', '18K (750 Diamond Gold)'), ('999', '999 Fine Silver')], default='22K', max_length=10)),
                ('weight_grams', models.DecimalField(decimal_places=3, help_text='Net weight in grams', max_digits=8)),
                ('making_charge_percent', models.DecimalField(decimal_places=2, default=12.0, help_text='Wastage / Making charge percentage', max_digits=5)),
                ('stone_price', models.IntegerField(default=0, help_text='Gemstone / Diamond value in INR')),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewels', to='accounts.jewelcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
