# Generated by Django 5.2.17 on 2026-10-06 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_registration_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('banner_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JewelCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('customer_type', models.CharField(choices=[('Royal VIP', 'Royal VIP Patron'), ('Privilege', 'Privilege Member'), ('Member', 'Heritage Member')], default='Privilege', max_length=30)),
                ('total_orders', models.IntegerField(default=1)),
                ('total_spent', models.IntegerField(default=365000)),
                ('last_purchase_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_spent'],
            },
        ),
        migrations.CreateModel(
            name='JewelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('product_name', models.CharField(max_length=200)),
                ('total_amount', models.IntegerField()),
                ('payment_method', models.CharField(default='Vault Gold Pay / UPI', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Crafting', 'Crafting'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock'), ('Made to Order', 'Made to Order'), ('Pre Order', 'Pre Order')], default='In Stock', max_length=30),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='base_price_override',
            field=models.IntegerField(blank=True, help_text='Explicit price override if specified', null=True),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='certification',
            field=models.CharField(blank=True, default='IGI & BIS Certified', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='crafting_time',
            field=models.CharField(blank=True, default='120 Hours', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='craftsmanship',
            field=models.CharField(blank=True, default='Handcrafted Temple Filigree', max_length=150),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='designer',
            field=models.CharField(blank=True, default='Master Artisan Arumugam', max_length=150),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='diamond_carat',
            field=models.CharField(blank=True, default='1.20 ct', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='gemstone_type',
            field=models.CharField(blank=True, default='Emerald', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='gemstone_weight',
            field=models.CharField(blank=True, default='4.32 ct', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='gemstones',
            field=models.CharField(blank=True, default='Emerald 4.32 ct, Natural Pearls', max_length=255),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='hallmark',
            field=models.CharField(blank=True, default='BIS 916 Hallmark', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='lifestyle_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='low_stock_threshold',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='origin',
            field=models.CharField(blank=True, default='Thanjavur Royal Guild', max_length=150),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Published', max_length=20),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='stock_quantity',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='tags',
            field=models.CharField(blank=True, default='Heritage, Temple, 22K Gold, Emerald', max_length=255),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='url_slug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='warehouse',
            field=models.CharField(blank=True, default='Chennai Vault 01', max_length=100),
        ),
        migrations.AlterField(
            model_name='jewelproduct',
            name='purity',
            field=models.CharField(choices=[('24K', '24K (999 Fine Gold)'), ('22K', '22K (BIS 916 Hallmark)'), ('18K', '18K (750 Diamond Gold)'), ('999', '999 Fine Silver'), ('950', '950 Platinum')], default='22K', max_length=10),
        ),
        migrations.AlterField(
            model_name='jewelproduct',
            name='weight_grams',
            field=models.DecimalField(decimal_places=3, default=25.0, help_text='Net weight in grams', max_digits=8),
        ),
        migrations.AddField(
            model_name='jewelproduct',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.jewelcollection'),
        ),
        migrations.CreateModel(
            name='JewelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(default='22K Gold', max_length=50)),
                ('size', models.CharField(default='Standard / 18 Inch', max_length=50)),
                ('stone', models.CharField(default='Emerald', max_length=100)),
                ('sku', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.IntegerField(default=365000)),
                ('stock', models.IntegerField(default=5)),
                ('weight_grams', models.DecimalField(decimal_places=3, default=45.0, max_digits=8)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='accounts.jewelproduct')),
            ],
        ),
        migrations.CreateModel(
            name='JewelVaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(default='Necklace', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.IntegerField(default=365000)),
                ('metal_purity', models.CharField(default='22K Gold', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
