# Generated by Django 5.2.17 on 2026-10-07 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jewelcollection_jewelcustomer_jewelorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_coins', models.DecimalField(decimal_places=2, default=5.0, max_digits=12)),
                ('last_daily_login_reward_date', models.DateField(blank=True, null=True)),
                ('total_coins_earned', models.DecimalField(decimal_places=2, default=5.0, max_digits=12)),
                ('total_spent_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reward', 'Reward'), ('recharge', 'Recharge'), ('debit', 'Debit'), ('purchase', 'Gold Purchase'), ('admin_credit', 'Admin Credit')], default='recharge', max_length=30)),
                ('reward_type', models.CharField(blank=True, default='', max_length=50)),
                ('direction', models.CharField(choices=[('credit', '+ CREDIT'), ('debit', '− DEBIT')], default='credit', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('coins_credited', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(default='wallet', max_length=30)),
                ('order_id', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(blank=True, default='Athirai Royal Vault', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
