# Generated by Django 5.2.17 on 2026-10-07 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userwallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelorder',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='coins_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total AUG Coins paid for order', max_digits=15),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='delivery_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='delivery_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='door_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='metal_purity',
            field=models.CharField(blank=True, default='22K Gold', max_length=50),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='product_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='town',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jewelorder',
            name='weight_grams',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='jewelorder',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='jewelorder',
            name='payment_method',
            field=models.CharField(default='AUG Coins', max_length=50),
        ),
        migrations.AlterField(
            model_name='jewelorder',
            name='total_amount',
            field=models.IntegerField(help_text='Total value in INR'),
        ),
    ]
